weedahm/data_collecting/urls.py
from django.urls import path

from . import views

app_name = 'data_collecting'
urlpatterns = [
    path('login', views.login, name='login'),
    path('authenticate', views.authenticate, name='authenticate'),
    path('logout', views.logout, name='logout'),
    path('', views.index, name='index'),
    path('submit', views.submit, name='submit'),
    path('delete', views.delete, name='delete'),
    path('patients', views.patients, name='patients'),
    #path('patientss/<str:selected_user_name>', views.patients_name, name='patients_name'),
    path('patient/<str:chart_id>', views.patient, name='patient'),

    path('ai_prescription', views.ai_prescription, name='ai_prescription'),
]

weedahm/weedahm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data_collecting.urls')),
]

weedahm/data_collecting/models.py
from django.db import models
from django.conf import settings
from jsonfield import JSONField
from django.contrib.auth import get_user_model

class Patient(models.Model):
    chart_id = models.CharField(max_length=8, unique=True)
    json_data = JSONField()
    created_date = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    created_user = models.ForeignKey(
        get_user_model(),
        on_delete = models.PROTECT
    )

    def __str__(self):
        return self.chart_id

weedahm/data_collecting/forms.py
# from django import forms
# from .models import 무엇

# class PostForm(forms.ModelForm):

#     class Meta:
#         model = 무엇
#         fields = ('왓', '음',)

weedahm/data_collecting/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib import auth
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.contrib.auth import get_user_model

from .models import Patient

import json


def login(request):
    if request.user.is_anonymous:
        context = {'is_anonymous': True}
        return render(request, 'data_collecting/login.html', context=context)
    return render(request, 'data_collecting/login.html')


def authenticate(request):
    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(request, username=username, password=password)
    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect(reverse('data_collecting:index'))
    else:
        return HttpResponseRedirect(reverse('data_collecting:login'))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('data_collecting:login'))


@login_required(login_url='/login')
def index(request):
    current_user = request.user
    context = {'user': current_user}
    return render(request, 'data_collecting/main.html', context=context)


@login_required(login_url='/login')
def patient(request, chart_id):
    try:
        patient = Patient.objects.get(chart_id=chart_id)
    except Patient.DoesNotExist:
        return JsonResponse({})

    last_modified = patient.created_date.strftime("%Y-%m-%d")
    patient.json_data["last_modified"] = last_modified
    if request.user.is_superuser:
        patient.json_data["created_user"] = str(patient.created_user)
    return JsonResponse(patient.json_data)


@login_required(login_url='/login')
def patients(request):
    n_createdBy = []
    selected_user_name = request.GET.get('selected_user')
    
    try:
        total_n_patients = Patient.objects.count()
        your_n_patients = Patient.objects.filter(created_user=request.user).count()

        if request.user.is_superuser:
            n_createdBy = list(Patient.objects.values('created_user__username').annotate(Count('created_user')).order_by('-created_user__count'))
            if selected_user_name is None:
                patient = Patient.objects.all().order_by("-chart_id")
            else:
                user_name = get_user_model().objects.get(username=selected_user_name)
                patient = Patient.objects.filter(created_user=user_name).order_by("-chart_id")
        else:
            patient = Patient.objects.filter(created_user=request.user).order_by("-chart_id")
    except Patient.DoesNotExist:
        return JsonResponse({})
    chart_ids = list((patient.values('chart_id')))
    return JsonResponse({'total_n_patients': total_n_patients,
                            'your_n_patients': your_n_patients,
                            'n_createdBy': n_createdBy,
                            'chart_id': chart_ids}, safe=False)

@login_required(login_url='/login')
def submit(request):
    received_json_data = json.loads(request.body)
    chart_id = received_json_data['chart_id']
    patient = Patient.objects.filter(chart_id=chart_id)
    if not patient.exists():
        p = Patient(
            chart_id=chart_id,
            json_data=received_json_data,
            created_user=request.user,
        )
        p.save()
        return HttpResponse("Save Success")
    else:
        if not request.user.is_superuser and patient[0].created_user != request.user:
            return HttpResponse("Already Created")
        elif received_json_data != patient[0].json_data:
            patient.update(json_data=received_json_data)
            return HttpResponse("Update Success")
        else:
            return HttpResponse("No Changes")


@login_required(login_url='/login')
def delete(request):
    received_json_data = json.loads(request.body)
    chart_id = received_json_data['deleteID']
    patient = Patient.objects.filter(chart_id=chart_id)
    if patient.exists() and patient[0].created_user == request.user:
        Patient.objects.filter(chart_id=chart_id).delete()
        return HttpResponse("Delete Success")
    else:
        return HttpResponse("Delete Rejected")


@login_required(login_url='/ai_prescription')
def ai_prescription(request):
    current_user = request.user
    context = {'user': current_user}
    return render(request, 'data_collecting/ai_prescription.html', context=context)

weedahm/datamining/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'datamining/datamining.html')

weedahm/data_collecting/templates/data_collecting/ai_prescription.html
{% extends "data_collecting/base.html" %}
{% block stylesheets %}
<link rel="stylesheet" href="/static/css/ai_prescription.css">
{% endblock stylesheets %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.ko.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script src="/static/js/ai_prescription.js"></script>
<!-- <script src="/static/js/custom.js"></script> -->
{% endblock scripts %}

{% block content %}
<div class='content--wrapper'>
    <div class='content__left'>
        <div class='content__left__patient-list box_with_border'>
            <div class="section-header">
                <span class="section-header-text">환자 리스트</span>
            </div>
            <div class="content__left__patient-list__layout scrollbar-default">
                <div class="force-overflow">
                    <div id="patientList" class="list-patient list-group list-group-flush" id="list-tab" role="tablist">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='content__right'>
        <div class="content__right__patient-info box_with_border">
            <div class="content__right__patient-info__item">
                <label for="input-chart-id">* 차트번호</label>
                <input id="input-chart-id" class="form-control" style="max-width: 120px;" disabled>
            </div>
            <div class="content__right__patient-info__item">
                <label for="input-gender">성별</label>
                <select id="input-gender" class="form-control" disabled>
                    <option value="W" selected>여</option>
                    <option value="M">남</option>
                </select>
            </div>
            <div class="content__right__patient-info__item">
                <label for="input-age">* 나이</label>
                <div class="input-group">
                    <input id="input-age" class="form-control" style="max-width: 70px;" disabled>
                    <div class="input-group-append">
                        <span class="input-group-text">세</span>
                    </div>
                </div>
            </div>
            <div class="content__right__patient-info__item">
                <label for="input-height">키</label>
                <div class="input-group">
                    <input id="input-height" class="form-control" style="max-width: 70px;" disabled>
                    <div class="input-group-append">
                        <div class="input-group-text">cm</div>
                    </div>
                </div>

            </div>
            <div class="content__right__patient-info__item">
                <label for="input-weight">몸무게</label>
                <div class="input-group">
                    <input id="input-weight" class="form-control" style="max-width: 70px;" disabled>
                    <div class="input-group-append">
                        <div class="input-group-text">kg</div>
                    </div>
                </div>

            </div>
            <span style="padding-top: 3px; margin-right: 16px;">혈압</span>
            <div class="content__right__patient-info__item">
                <label for="input-blood-high">수축기</label>
                <input id="input-blood-high" class="form-control" style="max-width: 70px;" disabled>
            </div>
            <div class="content__right__patient-info__item">
                <label for="input-blood-low">이완기</label>
                <input id="input-blood-low" class="form-control" style="max-width: 70px;" disabled>
            </div>

            <div class="content__right__patient-info__btn">
                <button class="btn btn-primary">
                    인공지능 처방전
                </button>
            </div>
        </div>
        <div class='content__right__ai-point box_with_border'>
            <div class="content__section-header">
                <span class="section-header-text">AI 카테고리별 점수</span>
                <button class="btn btn-secondary btn-sm" style="height: 28px; margin-top: 5px; margin-left:20px;">평균 점수
                    표기</button>
            </div>
            <div class="content__right__ai-point__layout">
                <div class="content__right__ai-point__layout__chart-wrapper">
                    <canvas class="content__right__ai-point__chart"></canvas>
                </div>
                <div class="content__right__ai-point__layout__discriptions">
                    <div class="content__right__ai-point__layout__discriptions__item">
                        <span class="content__right__ai-point__layout__discriptions__item__title">
                            담적
                            <span id="point-damzuk"
                                class="content__right__ai-point__layout__discriptions__item__point"></span>
                            <span class="content__right__ai-point__layout__discriptions__item__appix"> 점</span>
                        </span>
                    </div>
                    <div class="content__right__ai-point__layout__discriptions__item">
                        <span class="content__right__ai-point__layout__discriptions__item__title">
                            소화
                            <span id="point-sohwa"
                                class="content__right__ai-point__layout__discriptions__item__point"></span>
                            <span class="content__right__ai-point__layout__discriptions__item__appix"> 점</span>
                        </span>
                    </div>
                    <div class="content__right__ai-point__layout__discriptions__item">
                        <span class="content__right__ai-point__layout__discriptions__item__title">
                            신경
                            <span id="point-sinkyung"
                                class="content__right__ai-point__layout__discriptions__item__point"></span>
                            <span class="content__right__ai-point__layout__discriptions__item__appix"> 점</span>
                        </span>
                    </div>
                    <div class="content__right__ai-point__layout__discriptions__item">
                        <span class="content__right__ai-point__layout__discriptions__item__title">
                            순환
                            <span id="point-soonhwan"
                                class="content__right__ai-point__layout__discriptions__item__point"></span>
                            <span class="content__right__ai-point__layout__discriptions__item__appix"> 점</span>
                        </span>
                    </div>
                    <div class="content__right__ai-point__layout__discriptions__item">
                        <span class="content__right__ai-point__layout__discriptions__item__title">
                            기타
                            <span id="point-guitar"
                                class="content__right__ai-point__layout__discriptions__item__point"></span>
                            <span class="content__right__ai-point__layout__discriptions__item__appix"> 점</span>
                        </span>
                    </div>
                    <div class="content__right__ai-point__layout__discriptions__item">
                        <span class="content__right__ai-point__layout__discriptions__item__title">
                            특정
                            <span id="point-tukjung"
                                class="content__right__ai-point__layout__discriptions__item__point"></span>
                            <span class="content__right__ai-point__layout__discriptions__item__appix"> 점</span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class='content__right__ai-medicine box_with_border'>
            <div class="content__section-header">
                <span class="section-header-text">AI 추천 약재 처방</span>
            </div>
            <div class="content__right__ai-medicine__layout">
                <div class="drug-set-div">
                    <div class="content__right__ai-medicine__sum">
                        <div><h5>처방 1</h5></div>
                        <div>용량합계: <span id="drug-sum-1"></span> mg</div>
                    </div>
                    <div id="drug-set-1"
                        class="content__right__ai-medicine__list scrollbar-default list-group list-group-flush">

                    </div>
                </div>
                <div class="drug-set-div">
                    <div class="content__right__ai-medicine__sum">
                        <div><h5>처방 2</h5></div>
                        <div>용량합계: <span id="drug-sum-2"></span> mg</div>
                    </div>
                    <div id="drug-set-2"
                        class="content__right__ai-medicine__list scrollbar-default list-group list-group-flush">

                    </div>
                </div>
                <div class="drug-set-div">
                    <div class="content__right__ai-medicine__sum">
                        <div><h5>처방 3</h5></div>
                        <div>용량합계: <span id="drug-sum-3"></span> mg</div>
                    </div>
                    <div id="drug-set-3"
                        class="content__right__ai-medicine__list scrollbar-default list-group list-group-flush">

                    </div>
                </div>
            </div>
        </div>
        <!-- <div class='content__right__ai-medicine box_with_border'>
            <div class="content__section-header">
                <span class="section-header-text">온톨로지 추천 약재 처방</span>
            </div>
            <div class="content__right__ai-medicine__layout">
                <div class="content__right__ai-medicine__list"></div>
                <div class="content__right__ai-medicine__list1"></div>
                <div class="content__right__ai-medicine__list"></div>
            </div>
        </div> -->
    </div>
</div>

<div class="modal fade modal__request-error" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">서버 오류</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>인공지능 서버 요청에 실패하였습니다. 관리자에게 문의하세요</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

weedahm/data_collecting/templates/data_collecting/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" href="/static/images/logo.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.standalone.min.css"
        rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
        crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/custom.css">
    {% block stylesheets %}{% endblock stylesheets %}
    <title>Weedahm Bio</title>
</head>

<body>
    <div id="wrap">
        <div id="header">
            <div class="inner_header">
                {% include "data_collecting/header.html" %}
            </div>
        </div>
        <div id="container">{% block content %} {% endblock content %}</div>
        <div id="footer">{% include "data_collecting/footer.html" %}</div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>

    {% block scripts %}{% endblock scripts %}
</body>

</html>

weedahm/data_collecting/templates/data_collecting/chatbot.html
<style>
    @import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
@import url(//fonts.googleapis.com/earlyaccess/hanna.css);
@import url(//fonts.googleapis.com/earlyaccess/jejuhallasan.css);

    h2,h4{
        text-align: center;
      }
      /* .intro{
        background-color: #00968D;
      } */
      .intro{
          padding: 0px 40px 0px 40px;
          /* font-family: 'Jeju Gothic', sans-serif; */
          font-family: 'Hanna', sans-serif;
          /* font-family: 'Jeju Hallasan', cursive; */
      }
      .menu{
          padding: 20px 30px 20px 30px;
      }
      #main {
        max-width: 380px;
        margin: 0 auto;
        background-color: #00968D;
      }

      #main2{
        max-width: 380px;
        margin:auto;
        background-color: #e3e7ee;
      }
      .chatbot{
          position: relative;
          bottom: 75px;
          box-shadow: 0px 0px 9px 5px rgb(197, 193, 193);
      }
      .list-header{
          position: relative;
          height: 30px;
          border-bottom: 1px solid #00968D;
          padding: 0px 10px;
      }
      .lists{
        padding: 10px 0px 0px 0px;
      }
      .list_with_border{
        padding: 10px;
        background: #fff;
        box-shadow: 5px 5px 20px 0px rgb(197, 193, 193);
        border-radius: 15px;
      }
      #chat_img{
          position: relative; bottom:18px; right: 20px;
          height: 40px;
          width: auto;
      }
      #chat_img1{
          position: relative;
          height: 60px;
          width: auto;
      }
      #chat_img2{
          position: relative;bottom:14px; right: 15px;
          height: 30px;
          width: auto;
      }
      #chat_hello{
          position: relative;
          height: 45px;
          width: auto;
      }
      /* .list{
          width: 200px;
          padding: 5px;
          margin: 1px;
          font-weight: bold;
          background-color: beige;
      }

      .lists{
          display: none;
      }

      a{
          display: block;
          border-bottom: 1px solid #fff;
          text-decoration: none;
          background: #ddd;
          color: #fff;
          padding: 10px;
          font-weight: bold;
          width: 190px;
      }

      .lists a:hover{
          background: #000;
      }
      li{
          display: inline;
      }
      ul{
          display: inline;
      } */
</style>

<div class="fixed">
    <div class="chatbot">
        <div style="overflow-y: scroll; height:620px;">
        <div class="intro" id="main">
            <br>
            <h2 style="color: white">
            <img src="\static\images\doctorW.png" id="chat_hello"></img>
                안녕하세요
            <img src="\static\images\doctorM.png" id="chat_hello"></img></h2>
            <h4>위담한방병원 입니다.</h4>
            <h6>세계 최고의 의료진들과 함께하는 위담한방병원 입니다.
                24시간 언제든지 모르는 부분을 해결해줄 수 있습니다.
                궁금하신게 있으시다면 언제든지 물어보세요!
                오늘도 즐거운 하루 보내세요^^
            </h6>
            <br>
        </div>
        <div class="menu" id="main2">
            <div class="">
                <div class="list_with_border">
                    <div class="list-header">
                        <h6>위담한방병원</h6>
                    </div>
                    <div class="lists">
                            <ul>
                                <li><a href="http://weedahm.tistory.com/">한방병원 내과</a></li>
                                <li><a href="http://weedahm.com/main/main.php">강남점</a></li>
                                <li><a href="http://weedahm.com/wee/wee01/">상담문의</a></li>
                            </ul>
                    </div>
                </div>
            </div>
            <br>
            <div class="">
                <div class="list_with_border">
                    <div class="list-header">
                        <h6>위담한방병원 시스템</h6>
                    </div>
                    <div class="lists">
                            <ul>
                                <li><a href="example.com">온톨로지</a></li>
                                <li><a href="example.com">인공지능</a></li>
                                <li><a href="example.com">한방의료</a></li>
                            </ul>
                    </div>
                </div>
            </div>
            <br>
            <!-- <p class="list">위담한방병원 시스템</p>
            <div class="lists">
                <ul>
                    <li><a href="example.com">온톨로지</a></li>
                    <li><a href="example.com">인공지능</a></li>
                    <li><a href="example.com">한방의료</a></li>
                </ul>
            </div> -->
            <div class="">
                    <div class="list_with_border">
                        <div class="list-header">
                            <h6>프로그램 사용설명서</h6>
                        </div>
                        <div class="lists">
                                <ul>
                                    <li><a href="example.com">진단</a></li>
                                    <li><a href="example.com">처방</a></li>
                                    <li><a href="example.com">바디차트</a></li>
                                </ul>
                        </div>
                    </div>
            </div>
            <br>
            <div class="">
                    <div class="list_with_border">
                        <div class="list-header">
                            <h6>질문하기</h6>
                        </div>
                        <div class="lists">
                            <ul>
                                <li><a href="example.com">자주하는 질문</a></li>
                                <li><a href="example.com">직접 질문하기</a></li>
                                <li><a href="example.com">그 외</a></li>
                            </ul>
                        </div>
                    </div>
            </div>
            <input type="button" class="btn btn-info btn-custom" name="" value="문의하기">
          </div>
        </div>
    <!-- <div class="circle" id="chatbot_btn1"> -->
        <!-- <i class="fas fa-comment-alt"></i> -->
    <!-- </div> -->
    <!-- <div class="redCircle" id="chatbot_btn2">
    </div> -->
    </div>
</div>

<div class="fixed">
        <!-- <div class="circle" id="chatbot_btn1">
        <img src="\static\images\chat3.png" id="chat_img"></img>
        </div>

        <div class="circle" id="chatbot_btn1">
        <img src="\static\images\cancel1.png" id="chat_img2"></img>
        </div> -->

        <div class="" id="chatbot_btn1">
        <img src="\static\images\chat1.png" id="chat_img1"></img>
        </div>
</div>

<!-- <img id="my_image" src="\static\images\chat1.png"></img> -->

weedahm/data_collecting/templates/data_collecting/eav_select_options.html
<option selected>위</option>
<option>경추</option>
<option>심장</option>
<option>뇌</option>
<option>전립선,방광/자궁,방광</option>
<option>폐</option>
<option>간</option>
<option>담</option>
<option>갑상선/부갑상선/췌장</option>
<option>혈관/대동맥</option>
<option>소장</option>
<option>대장</option>
<option>피부</option>
<option>안/이/비</option>
<option>복강</option>

weedahm/data_collecting/templates/data_collecting/footer.html
<div class="company-info">
    <p class="footer">
        회사소개 <span class="border-left"> </span>
        인재채용 <span class="border-left"> </span>
        제휴제안 <span class="border-left"> </span>
        개인정보처리방침 <span class="border-left"> </span>
        위담바이오 <span class="border-left"> </span>
        위담한방병원 <span class="border-left"> </span>
    </p>
</div>

weedahm/data_collecting/templates/data_collecting/header.html
<div class="logo">
    <a href='/'><img src="/static/images/logo.png"></a>
</div>
<div class="header__menu">
    <span class="header__menu__item"><a class="non-active" href="/">환자 정보 입력</a></span>
    <span class="header__menu__item"><a class="non-active" href="/ai_prescription">인공지능 처방전</a></span>
</div>
{% if is_anonymous %}
{% else %}
{% if user %}
<div class="header__logout">
    <span>환영합니다! {{ user.username }}님</span>
    <a class="btn btn-secondary btn-sm" style="margin-left: 1rem" href="/logout">로그아웃</a>
</div>
{% endif %}
{% endif %}

weedahm/data_collecting/templates/data_collecting/login.html
{% extends "data_collecting/base.html" %} {% block content %}
<div style="margin-top:20px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div style="float:left; margin-bottom: 20px">
                <div class="panel-title">위담바이오 로그인</div>
            </div>
            <div style="float:right; margin-bottom: 20px">
                <a href="#">문의</a>
            </div>
        </div>

        <div class="panel-body">
            <form class="form-horizontal" action="{% url 'data_collecting:authenticate' %}" method="post">
                {% csrf_token %}
                <div style="margin-bottom: 25px" class="input-group">
                    <input type="text" class="form-control" name="username" placeholder="아이디">
                </div>

                <div style="margin-bottom: 25px" class="input-group">
                    <input type="password" class="form-control" name="password" placeholder="패스워드">
                </div>

                <div style="margin-top:10px" class="form-group">
                    <div class="col-sm-12 controls">
                        <input type="submit" id="btn-login" class="btn btn-success" value="로그인">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

weedahm/data_collecting/templates/data_collecting/prescription-table.html
<div class="pre-table-scroll pre-table scrollbar-default">
    <table class="table table-hover table-striped">
        <tbody></tbody>
    </table>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <select class="form-control">
            {% include "data_collecting/prescription_select_options.html" %}
        </select>
    </div>
    <div class="form-group col-md-3">
        <input type="number" step="0.1" class="form-control doses" placeholder="mg">
    </div>
    <div class="form-group col-md-3">
        <button type="button" class="pre-btn form-control btn btn-success">추가</button>
    </div>
</div>

weedahm/data_collecting/templates/data_collecting/prescription_select_options.html
<option selected>허한</option>
<option>실열</option>
<option>청쾌</option>
<option>홍소</option>
<option>소화</option>
<option>가스@</option>
<option>가스</option>
<option>음적</option>
<option>심혈</option>
<option>협심</option>
<option>속쓰림</option>
<option>체기</option>
<option>변비</option>
<option>보약</option>
<option>설사</option>
<option>갱년기</option>
<option>어지럼</option>
<option>두통</option>
<option>소체</option>
<option>중체</option>
<option>실체</option>
<option>수자심</option>
<option>옻</option>
<option>수면</option>
<option>수면(2)</option>
<option>총명</option>
<option>피부</option>
<option>여드름</option>
<option>아토피</option>
<option>두드러기</option>
<option>관절</option>
<option>당뇨</option>
<option>BC</option>